image:
  name: rasa/rasa:2.8.0
  entrypoint: [""]

services:
  - name: "rasa/duckling"
    alias: "duck"

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - style
  - test
  - deploy

check_style_with_black:
  before_script:
    - export PATH=/app/bin/:/app/:$PATH
    - export PYTHONPATH=/app/:$PYTHONPATH
    - pip install -t /app/ black==22.3.0
  stage: style
  script:
    - black --check .

test_bocadelobo_domain:
  when: manual
  before_script:
    - export PATH=/app/bin/:/app/:$PATH
    - export PYTHONPATH=/app/:$PYTHONPATH
    - pip install -r ./docker/development-requirements.txt -t /app
  stage: test
  variables:
    RASA_DUCKLING_HTTP_URL: "http://duck:8000"
  script:
    - cd bot && rasa train --domain domain.bocadelobo.yml
    - rasa test --out results/ --fail-on-prediction-errors --nlu data/nlu.yml --cross-validation
    - rasa test core --fail-on-prediction-errors --out results/results-core-test

test_default_domain:
  when: manual
  before_script:
    - export PATH=/app/bin/:/app/:$PATH
    - export PYTHONPATH=/app/:$PYTHONPATH
    - pip install -r ./docker/development-requirements.txt -t /app
  stage: test
  variables:
    RASA_DUCKLING_HTTP_URL: "http://duck:8000"
  script:
    - cd bot && rasa train --domain domain.default.yml
    - rasa test --out results/ --fail-on-prediction-errors --nlu data/nlu.yml --cross-validation
    - rasa test core --fail-on-prediction-errors --out results/results-core-test

test_actions:
  when: manual
  before_script:
    - export PATH=/app/bin/:/app/:$PATH
    - export PYTHONPATH=/app/:$PYTHONPATH
    - pip install -r ./docker/development-requirements.txt -t /app
  stage: test
  script:
    - cd bot 
    - python3 -m pytest

deploy_to_dev:
  image: 
    name: debian:stable
  when: manual
  stage: deploy
  before_script:
    - apt update && apt install -y bash git
  script:
    - /bin/sh -c 'git clone -b stable --depth=1 https://gitlab+deploy-token-155341:xWz-bGxYnvTLcZCzsHEG@gitlab.com/pencillabs/infraestructure/core.git'
    - cd core && bin/pencilctl build rasadefault -e dev -c prod -b develop --no-cache --push
  only:
    refs:
      - develop
