image: python:3.7-slim-buster

stages:
  - style
  - test

style:
  before_script:
    - apt get musl-dev gcc
    - pip install black
  stage: test
  script:
    - black --check .


test:
  before_script:
    - apt update
    - apt get curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext rust cargo
    - curl -O https://bootstrap.pypa.io/get-pip.py
    - python3 get-pip.py
    - pip install --upgrade pip
    - pip install -r /docker/dependencies/requirements-development.txt
    - pip install --use-deprecated=legacy-resolver --no-cache-dir -r /docker/dependencies/x-requirements.txt
    - python3 -c "import nltk; nltk.download('stopwords');"
    - python3 -m spacy download pt_core_news_sm
    - rasa train
  stage: test
  script: 
    - rasa test nlu --nlu data/nlu.yml --cross-validation
    - rasa test core --fail-on-prediction-errors --out results/results-core-test
    - python3 -m pytest  -e JWT_SECRET=testing_secret_value