image:
  name: rasa/rasa:3.3.6
  entrypoint: [""]

services:
  - name: "rasa/duckling"
    alias: "duck"

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

stages:
  - style
  - test
  - deploy

check_style_with_black:
  before_script:
    - export PATH=/app/bin/:/app/:$PATH
    - export PYTHONPATH=/app/:$PYTHONPATH
    - pip install -t /app/ black==22.3.0
  stage: style
  script:
    - black --check .
  tags:
    - k8s


test_domain:
  before_script:
    - export PATH=/app/bin/:/app/:$PATH
    - export PYTHONPATH=/app/:$PYTHONPATH
    - pip install -r ./docker/development-requirements.txt -t /app
  stage: test
  variables:
    RASA_DUCKLING_HTTP_URL: "http://duck:8000"
  script:
    - cd bot && rasa train
    - RASA_DOMAIN=bp rasa test --fail-on-prediction-errors
  tags:
    - k8s

test_actions:
  before_script:
    - export PATH=/app/bin/:/app/:$PATH
    - export PYTHONPATH=/app/:$PYTHONPATH
    - pip install -r ./docker/development-requirements.txt -t /app
  stage: test
  script:
    - cp .env.sample bot/.env
    - cd bot 
    - python3 -m pytest
  tags:
    - k8s
