version: "3.4"

x-bot-common-build: &bot-common-build
  build:
    context: .
    dockerfile: ./docker/Dockerfile

x-bot-common: &bot-common
  env_file:
    - env/auth.env
    - env/servers.env

services:
  # =============================== Webchat =================================
  # Nginx container to run rasa webchat
  webchat:
    image: nginx
    volumes:
      - ./webchat/:/usr/share/nginx/html/
    ports:
      - 8001:80

  # =============================== Coach =================================
  # All the models are trained by this coach.
  coach:
    <<: *bot-common-build
    <<: *bot-common
    volumes:
      - ./bot/:/bot/
    entrypoint: "make train domain=${domain}"

  # ================================= Bot =====================================
  # Rasa open source server
  bot:
    <<: *bot-common-build
    <<: *bot-common
    container_name: bot
    restart: unless-stopped
    volumes:
      - ./bot/:/bot/
    ports:
      - 5006:5006
      - 5004:5004
      - 5005:5005
    # https://github.com/docker/compose/issues/6767
    networks:
      - bot-network
    entrypoint: "make api"

  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    <<: *bot-common-build
    <<: *bot-common
    container_name: actions
    ports:
      - 5055:5055
    volumes:
      - ./bot:/bot
    entrypoint: "make actions"
    environment:
      JWT_SECRET: RRrWj+H2QEqV9O7iKBrU0zuB
    networks:
      - bot-network

  # ================================= Duckling ================================
  # Duckling HTTP extractor for entities such as email, date, amounts...
  duckling:
    container_name: duck
    image: "rasa/duckling"
    ports:
      - 6800:8000
    networks:
      - bot-network


networks:
  bot-network:
    driver: bridge
