version: "3.4"

x-bot-common-build: &bot-common-build
  build:
    context: .
    dockerfile: ./docker/Dockerfile

x-bot-common: &bot-common
  env_file:
    - .env

services:
  # =============================== Coach =================================
  # All the models are trained by this coach.
  coach:
    <<: *bot-common-build
    <<: *bot-common
    volumes:
      - ./bot/:/bot/
    entrypoint: "make train"

  # ================================= Bot =====================================
  # Rasa open source server
  bot:
    <<: *bot-common-build
    <<: *bot-common
    container_name: bot
    restart: unless-stopped
    volumes:
      - ./bot/:/bot/
    ports:
      - 5006:5006
      - 5004:5004
      - 5005:5005
    # https://github.com/docker/compose/issues/6767
    networks:
      - bot-network
    entrypoint: "make api"

  # ================================= Actions =================================
  # Rasa middleware used to connect with external APIs.
  actions:
    <<: *bot-common-build
    <<: *bot-common
    container_name: actions
    ports:
      - 5055:5055
    volumes:
      - ./bot:/bot
    entrypoint: "make actions"
    environment:
      JWT_SECRET: RRrWj+H2QEqV9O7iKBrU0zuB
    networks:
      - bot-network

  # ================================= Duckling  ==================================
  # Duckling HTTP extractor for entities such as email, date, amounts...
  duckling:
    container_name: duck
    image: "rasa/duckling"
    ports:
      - 6800:8000
    networks:
      - bot-network

  redis:
    image: redis:7.2.3-bookworm
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - bot-network

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=rasa
      - POSTGRES_USER=rasa
      - POSTGRES_DB=rasa
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
